# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "yzbao'blog"

author:
  github:           yzbaoo
  email:            yzb99666@163.com
  # 暂时当成segmentfault
  tumblr:           yzbaoo

copyright:
  year:             2017
  name:             yzb

# Google-analytics
google-analytics:
  id:               "UA-113291156-1"

# Disqus
disqus:
  id:               "安静点"

# URL
url:                "https://yzbaoo.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4004" # use this url when you develop
baseurl:            "/yzbaoo.github.io" # the subpath of your site, e.g. /blog
# baseurl:                "http://localhost:4004" # use this url when you develop


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:          	America/New_York
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  css_class: 'highlight'

# Navigation
nav:
  - name:           "关于"
    url:            "/about"
  - name:           "文章"
    url:            "/archive"
  - name:           "标签"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/yzbaoo"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
# fangwenliangjilu
leancloud:
  enable: true
  app_id: ATwmUcIRwyVC5A3vIPkaOmez-gzGzoHsz
  app_key: NjylQxeLR3uMGmdmjFKJaBWH

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
port: 4004